#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZWY4NjU0ZmY3YWYyM2IyNDYwNWQ4ZmQwNTZiMmUzMmNlMmZiYjUxNmZhMDNmZTRiOGYzZTljNzliYjY2NGI5MjliNmFlY2Q0OTY3ZjZlNTNkZjI4NzlhZTQ4M2Y3MTQ1YTc1Mw==

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
